# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
gems:                [jekyll-paginate]
permalink:           pretty
markdown:            kramdown

#relative_permalinks: true

# Setup
title:               Snippets
tagline:             'some notes and snippets'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://adyagit.github.io/snippets
baseurl:             'https://github.com/adyagit/snippets'
paginate:            5

# About/contact
author:
  name:              Srikanth Adya
  url:               https://twitter.com/colorlungi
  email:             sri.adya@gmail.com

# Custom vars
version:             1.0.0
pages_list:
  About: '/snippets/about'
  Archive: '/snippets/archive'
  Feed: '/snippets/atom.xml'
